name: Deploy Main
on:
  push:
    branches: [ main ]

jobs:
  test_contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: cd core/ && yarn install && yarn test
        env:
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DATABASE_NAME: chat_clin
          DATABASE_HOST: localhost
          DATABASE_TYPE: postgres
  deploy_api:
    needs: test_contract
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/agnostic-api/core
            git pull origin main
            yarn install
            npx sequelize db:migrate
            pm2 restart api-ddd