name: Pull request validate contract
on:
  pull_request:
    types: [ labeled ]
  pull_request_review:
    types: [ submitted ]

jobs:
  test_contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      env:
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        DATABASE_NAME: chat_clin
        DATABASE_HOST: localhost
        DATABASE_TYPE: postgres
      - run: yarn install && yarn test