name: Tester Contract
on:
  push:
    branches: [ main ]

jobs:
  test_contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: cd core/ && yarn install && yarn test
